// <auto-generated />
namespace Moshavit.DataBase.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class add_TypeMember_To_Survey : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_TypeMember_To_Survey));
        
        string IMigrationMetadata.Id
        {
            get { return "201410080656083_add_TypeMember_To_Survey"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
