// <auto-generated />
namespace Moshavit.DataBase.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class add_Email_Template : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_Email_Template));
        
        string IMigrationMetadata.Id
        {
            get { return "201410142128231_add_Email_Template"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
